permalink: pretty
auto: true
markdown: redcarpet2
var:
  home_path: /
  archive_path: /archive/
  categories_path : /categories/
  tags_path : /tags/
redcarpet:
  extensions:
    ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]